--1) what is the total revenue generated by male vs female customers? 
SELECT Gender, SUM([Purchase_Amount]) AS Total_Revenue
FROM customer
GROUP BY gender;

--2) which customer uses a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount FROM customer
where discount_applied ='Yes' and purchase_amount >=(select AVG(purchase_amount) from customer)

--3) which are the top 5 products with highest average review rating?
SELECT TOP 5 
    item_purchased,
    ROUND(AVG(review_rating),2) AS Average_Product_Rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;

--4) compare the average purchase amount between standard and express shipping.
select shipping_type,
CAST(AVG(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(10,2)) As avg_shipping_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5) Do subscribed customer spend more? compare average spend and total revenue between subscribers and non_subscribers.
SELECT 
    subscription_status,
	COUNT (customer_id) as total_customers,
    CAST(AVG(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(10,2)) AS avg_spend,
    CAST(SUM(CAST(purchase_amount AS DECIMAL(10,2))) AS DECIMAL(12,2)) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

--6)which 5 products have the highest percentage of purchase with discounts applied?
SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*), 2
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

--7) segmnt customers into new, returning and loyal based on their number of previous purchase , and show the count of each segmnt.
WITH customer_type AS (
    SELECT 
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

--8) what are top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

--9) are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;

--10) what is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




 

